### ISSUE TITLE
I am unable to download the decorators

### ISSUE THREAD

**Issue by Anoop-Suresh** [dnmellen/django-rest-friendship#3]
from rest_framework.decorators import detail_route, list_route

ErrorMessage

  File "/home/anoop/PycharmProjects/Zartech1/socialmedia/home/views.py", line 18, in <module>
    from rest_framework.decorators import detail_route, list_route
ImportError: cannot import name 'detail_route'

**Comment by pmburu** [comment]
@Anoop-Suresh 

`from rest_framework.decorators import action`

`  @action(detail=True)
    def requests(self, request):
        friend_requests = Friend.objects.unrejected_requests(user=request.user)
        return Response(FriendshipRequestSerializer(friend_requests, many=True).data)`

**Comment by sflems** [comment]
I've refactored the current release to be compatible with Django 4 and DRF 3.13. Would you be interested in a new PR? It does include some breaking changes with the URLs and includes some added serializers. Otherwise, the original functionality remains.

Cheers!
Scott

**Comment by dnmellen** [comment]
Absolutely, Thanks @sflems.
